### ISSUE TITLE
I wonder how to get the tokens.xml when I use iphone

### ISSUE THREAD

**Issue by boat320** [jimktrains/freeotp-cli#1]

**Comment by boat320** [comment]
I wonder how to get the tokens.xml when I use iphone.

**Comment by jimktrains** [comment]
I'm not sure, as I don't have any Apple devices. There is an forked and updated version of the app (for not from RedHat iirc) that has exporting built in. Perhaps there is an iPhone equivalent or alternative with similar functionality?
